#!/bin/sh

# A hook script that generates production buil and documentation before a push
# Usefull if you wish not to have to run those commands before merging a branch
# Generates a fixed, generic commit message

npm run production
npm run documentation
git add dist/*
git add documentation/*
git commit -m "pre-push - build and documentation auto-update"
